services:
  # Oracle service (label used to access the service container)
  oracle:
    # Docker Hub image (feel free to change the tag "latest" to any other available one)
    image: gvenzl/oracle-xe:latest
    # Provide passwords and other environment variables to container
    environment:
      ORACLE_PASSWORD: oracle
      APP_USER: app
      APP_USER_PASSWORD: app_password
    # Forward Oracle port
    ports:
      - 1521:1521
      - 5500:5500
